### ISSUE TITLE
Unable to fetch NXP source

### ISSUE THREAD

**Issue by abferm** [balena-os/balena-fsl-arm#385] opened 2023-04-21 16:21 UTC
`ERROR: imx-boot-1.0-r0 do_fetch: Fetcher failure for URL: 'git://source.codeaurora.org/external/imx/imx-mkimage.git;protocol=https;branch=lf-5.10.72_2.2.0'. Unable to fetch URL from any source.`

This is likely because CodeAura closed down their git repositories at the end of March.
https://bye.codeaurora.org/

**Comment by floion** [comment] 2023-04-24 07:18
Hi @abferm indeed, that is the cause.
We first need to have https://github.com/Freescale/meta-freescale/pull/1512 merged and then we can pull it in our repo.

**Comment by otavio** [comment] 2023-04-24 10:39
@floion, we merged it already. I hope it helps.

**Comment by floion** [comment] 2023-04-24 14:20
Thanks so much @otavio !
@abferm created https://github.com/balena-os/balena-fsl-arm/pull/389 to fix this issue here

**Comment by floion** [comment] 2023-04-24 14:47
https://github.com/balena-os/balena-fsl-arm/pull/389 has been merged. Feel free to reopen if you still see this issue

**Closed by floion** 2023-04-24 14:47 UTC
